#!/bin/sh

### SXHKD (serios for keybinds) ###
pgrep -x sxhkd > /dev/null || sxhkd &

### AUTOSTART ###
setxkbmap -model pc104 -layout lv,ru -variant ,phonetic_YAZHERTY -option grp:shifts_toggle &
xrdb -merge ~/.Xresources &
lxsession &
nm-applet &
pgrep -x xfce4-clipman > /dev/null || xfce4-clipman &
nitrogen --restore &
flameshot &
picom --experimental-backends &
dunst &
xautolock -corners "-000" -cornersize 28 -time 5 -locker screenlock &
mpd &
$HOME/.config/polybar/launch.sh &

### MONITORS ###
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-0 -d 0

### MAIN ###
bspc config border_width               2
bspc config window_gap                 10
bspc config split_ratio                0.5

bspc config single_monocle             true
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_by_distance          true
bspc config focus_follows_pointer      true
bspc config history_aware_focus        true
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true

### COLOURING ###
bspc config focused_border_color "#888888"
bspc config normal_border_color  "#282828"
bspc config active_border_color  "#282828"

### RULES ###
bspc rule -a Steam state=floating
bspc rule -a discord desktop='^9'
bspc rule -a OpenTabletDriver.UX.Gtk state=floating
bspc rule -a Virt-manager state=floating
bspc rule -a zoom state=floating
bspc rule -a minecraft-launcher state=floating
bspc rule -a KeyOverlay state=floating
bspc rule -a robloxplayerlauncher.exe state=floating
bspc rule -a flameshot state=floating
