[window]

padding.x = 20
padding.y = 20

[font]

normal.family = "Iosevka Nerd Font"
bold.family = "Iosevka Nerd Font"
italic.family = "Iosevka Nerd Font"
bold_italic.family = "Iosevka Nerd Font"

offset = { x = 0, y = 6 }
glyph_offset = { x = 0, y = 3 }

size = 12.5

[cursor]
style = { shape = "beam", blinking = "always" }

[colors]
draw_bold_text_with_bright_colors = true
